name: Train Model

on:
  push:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          activate-environment: ''

      - name: Install Dependencies
        run: |
          pip install mlflow==2.19.0
          pip install pandas
          pip install scikit-learn

      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run . --experiment-name Telco_Customer_Churn

      - name: Upload Model Artifact
        uses: actions/upload-artifact@v4
        with:
          name: churn-model
          path: |
            MLProject/*.pkl
            MLProject/mlruns/**